import angular from 'angular';

import appRun from './config/app.run';
import appConfig from './config/app.config';
import constants from './config/app.constants';
import 'angular-ui-router';
import 'toastr';
// Import our templates file (generated by Gulp)
// Import our app functionaity
import './layout';
// import './components';
// import './home';
// import './profile';
// import './article';
import './services';
// import './auth';
// import './settings';
import './markets';
window.cfg = require('../../configs/ropsten.js');

// Create and bootstrap application
const requires = [
    'ui.router',
    'app.layout',
    'app.markets',
    'app.services'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
    strictDi: true
});
